### ISSUE TITLE
No bson module in kraken-agent

### ISSUE THREAD

**Issue by bdekany** [certsocietegenerale/kraken#1]
Hi there~

You moved from pickle to bson but didn't import bson into App.zip.
What was the problem with tickle?

**Comment by tomchop** [comment]
Pickle introduced a critical security issue. It has therefore been removed.

**Comment by bdekany** [comment]
OK! Which bson module do you recommand (MangoDB vs Python3)?
http://bsonspec.org/implementations.html

**Comment by tomchop** [comment]
We use the native python `json` module
